// Code generated by go-swagger; DO NOT EDIT.

// Package wesniff wesniff
//
//  api server
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/json
//
// swagger:meta
package wesniff
