// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Person person
//
// swagger:model Person
type Person struct {

	// citizenship
	Citizenship string `json:"citizenship,omitempty"`

	// date of birth
	DateOfBirth string `json:"dateOfBirth,omitempty"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// gender
	Gender string `json:"gender,omitempty"`

	// id number
	IDNumber string `json:"idNumber,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// nationality
	Nationality string `json:"nationality,omitempty"`

	// pep sanction match
	PepSanctionMatch string `json:"pepSanctionMatch,omitempty"`

	// place of birth
	PlaceOfBirth string `json:"placeOfBirth,omitempty"`

	// year of birth
	YearOfBirth string `json:"yearOfBirth,omitempty"`
}

// Validate validates this person
func (m *Person) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Person) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Person) UnmarshalBinary(b []byte) error {
	var res Person
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
