// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RiskLabel risk label
//
// swagger:model RiskLabel
type RiskLabel struct {

	// category
	Category string `json:"category,omitempty"`

	// label
	Label string `json:"label,omitempty"`
}

// Validate validates this risk label
func (m *RiskLabel) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RiskLabel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RiskLabel) UnmarshalBinary(b []byte) error {
	var res RiskLabel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
