// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// SuccessCode Status message for successful request
//
// swagger:model SuccessCode
type SuccessCode float64

// Validate validates this success code
func (m SuccessCode) Validate(formats strfmt.Registry) error {
	return nil
}
