// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserCreateDto user create dto
//
// swagger:model UserCreateDto
type UserCreateDto struct {
	roleField *string

	// email
	// Required: true
	// Format: email
	Email *strfmt.Email `json:"email" valid:"email"`
}

// Role gets the role of this subtype
func (m *UserCreateDto) Role() *string {
	return m.roleField
}

// SetRole sets the role of this subtype
func (m *UserCreateDto) SetRole(val *string) {
	m.roleField = val
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *UserCreateDto) UnmarshalJSON(raw []byte) error {
	var data struct {

		// email
		// Required: true
		// Format: email
		Email *strfmt.Email `json:"email" valid:"email"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Role *string `json:"role,omitempty"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result UserCreateDto

	result.roleField = base.Role

	result.Email = data.Email

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m UserCreateDto) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// email
		// Required: true
		// Format: email
		Email *strfmt.Email `json:"email" valid:"email"`
	}{

		Email: m.Email,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Role *string `json:"role,omitempty"`
	}{

		Role: m.Role(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this user create dto
func (m *UserCreateDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var userCreateDtoTypeRolePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["admin","member"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		userCreateDtoTypeRolePropEnum = append(userCreateDtoTypeRolePropEnum, v)
	}
}

// property enum
func (m *UserCreateDto) validateRoleEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, userCreateDtoTypeRolePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UserCreateDto) validateRole(formats strfmt.Registry) error {

	if swag.IsZero(m.Role()) { // not required
		return nil
	}

	// value enum
	if err := m.validateRoleEnum("role", "body", *m.Role()); err != nil {
		return err
	}

	return nil
}

func (m *UserCreateDto) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	if err := validate.FormatOf("email", "body", "email", m.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserCreateDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserCreateDto) UnmarshalBinary(b []byte) error {
	var res UserCreateDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
